const dict = {
  en: {
    "nav.home": "Home",
    "nav.papers": "Papers",
    "nav.leaderboard": "Leaderboard",
    "nav.blog": "Blog",

    "hero.badge": "FDU-NLP · AAAI 2024 · EMNLP 2025 · ACL 2026",
    "hero.title1": "Comprehensive Evaluation for ",
    "hero.title2": "Large Language Models",
    "hero.desc": "LLMEval is a research initiative from {lab}, building rigorous and fair evaluation frameworks for LLMs across 13+ academic disciplines, medical AI, and 220,000+ generative questions.",
    "hero.lab": "Fudan NLP Lab",
    "hero.btn.papers": "Explore Papers",
    "hero.btn.leaderboard": "View Leaderboard",
    "hero.stat.projects": "Research Projects",
    "hero.stat.models": "Models Evaluated",
    "hero.stat.questions": "Evaluation Questions",
    "hero.stat.disciplines": "Academic Disciplines",

    "home.featured": "Featured Research",
    "home.featured.desc": "Our latest publications in LLM evaluation.",
    "home.viewAll": "View all papers",
    "home.cta.title": "Participate in LLMEval",
    "home.cta.desc": "LLMEval is open to the public. Feel free to explore our code and data on GitHub, or contact us for collaboration.",
    "home.cta.apply": "Apply for Evaluation",
    "home.cta.github": "View on GitHub",

    "papers.title": "Papers",
    "papers.desc": "All publications from the LLMEval research series.",
    "papers.year": "Year:",
    "papers.topic": "Topic:",
    "papers.showing": "Showing {n} of {total} papers",
    "papers.noMatch": "No papers match the selected filters.",
    "papers.clear": "Clear filters",
    "papers.relatedDatasets": "Related Datasets",

    "lb.title": "Leaderboard",
    "lb.desc": "Model performance rankings across all LLMEval benchmarks.",
    "lb.fair.desc": "220K generative questions, 13 academic disciplines, ~60 models over a 30-month longitudinal study.",
    "lb.med.desc": "2,996 physician-validated clinical questions, 5 medical dimensions, 13 models (open-source, closed-source, specialized).",
    "lb.eval1.desc": "Phase I general evaluation: 17 categories, 453 questions, 2,186 annotators + GPT-4 scoring.",
    "lb.eval2.desc": "Phase II professional domain evaluation: 12 disciplines, 480 questions (objective + subjective).",
    "lb.about": "About the Evaluations",
    "lb.about.fair": "LLMEval-Fair (ACL 2026): 220,000 graduate-level generative questions across 13 disciplines. Each model answers 1,000 randomly sampled questions. Absolute score (0-100) reflects raw performance; relative score measures the gap to the SOTA model. Discipline scores on a 10-point scale. GPT-4 Turbo judges each question on a 0-3 rubric.",
    "lb.about.med": "LLMEval-Med (EMNLP 2025): 2,996 questions from real electronic health records and expert-designed clinical scenarios, across 5 dimensions (MK, MLU, MR, MSE, MTG). Usability rate (%) = proportion of responses scoring 4+ (automated, 0-5) or 5+ (MTG, human-evaluated, 0-7). Human-machine agreement: 92.36%.",
    "lb.about.eval1": "LLMEval-1 (AAAI 2024): 17 categories, 453 questions, five dimensions (correctness, fluency, informativeness, logic, harmlessness, 0-3 scale). 2,186 annotators contributed 243,337 annotations. Pairwise comparison (0-1) also provided.",
    "lb.about.eval2": "LLMEval-2 (AAAI 2024): 12 disciplines, 480 questions, objective (max 5 pts) + subjective (max 14 pts). Total normalized to 0-100.",
    "lb.submit": "Want to submit your model for evaluation? Contact us at",
    "lb.or": "",
    "lb.search": "Search models...",
    "lb.allTypes": "All Types",

    "blog.title": "Blog",
    "blog.desc": "Updates and announcements from the LLMEval team.",
    "blog.empty": "No blog posts yet. Stay tuned!",
    "blog.readMore": "Read more",
    "blog.back": "Back to Blog",

    "footer.desc": "LLM evaluation frameworks by Fudan NLP Lab.",
    "footer.research": "Research",
    "footer.links": "Links",
    "footer.contact": "Contact",
    "footer.github": "GitHub Organization",
    "footer.platform": "LLMEval Platform",
    "footer.copyright": "LLMEval Project · Fudan NLP Lab. All rights reserved.",

    "common.all": "All",
  },
  zh: {
    "nav.home": "首页",
    "nav.papers": "论文",
    "nav.leaderboard": "排行榜",
    "nav.blog": "博客",

    "hero.badge": "复旦NLP · AAAI 2024 · EMNLP 2025 · ACL 2026",
    "hero.title1": "大语言模型",
    "hero.title2": "综合评测体系",
    "hero.desc": "LLMEval 是{lab}推出的系列评测研究，构建严谨、公平、全面的大语言模型评测框架，覆盖13+学科门类、医学AI及22万+生成式评测题目。",
    "hero.lab": "复旦大学NLP实验室",
    "hero.btn.papers": "浏览论文",
    "hero.btn.leaderboard": "查看排行榜",
    "hero.stat.projects": "研究项目",
    "hero.stat.models": "已评测模型",
    "hero.stat.questions": "评测题目",
    "hero.stat.disciplines": "学科门类",

    "home.featured": "精选研究",
    "home.featured.desc": "LLM评测领域的最新发表成果。",
    "home.viewAll": "查看全部论文",
    "home.cta.title": "参与 LLMEval 评测",
    "home.cta.desc": "LLMEval 已向公众开放，欢迎在 GitHub 上查看我们的代码和数据，或联系我们进行合作。",
    "home.cta.apply": "申请评测",
    "home.cta.github": "访问 GitHub",

    "papers.title": "论文",
    "papers.desc": "LLMEval 系列的全部发表成果。",
    "papers.year": "年份：",
    "papers.topic": "主题：",
    "papers.showing": "显示 {n} / {total} 篇论文",
    "papers.noMatch": "没有符合筛选条件的论文。",
    "papers.clear": "清除筛选",
    "papers.relatedDatasets": "关联数据集",

    "lb.title": "排行榜",
    "lb.desc": "LLMEval 全部评测基准的模型性能排名。",
    "lb.fair.desc": "22万生成式题目，13个学科门类，历时30个月纵向研究，评测近60个模型。",
    "lb.med.desc": "2,996道经医生验证的临床题目，5个医学维度，13个模型（开源/闭源/专用）。",
    "lb.eval1.desc": "第一期综合评测：17大类、453题，2,186名标注者 + GPT-4自动评分。",
    "lb.eval2.desc": "第二期专业领域评测：12个学科、480题（客观题+主观题）。",
    "lb.about": "关于评测方法",
    "lb.about.fair": "LLMEval-Fair（ACL 2026）：22万道研究生级别生成式题库，覆盖13个学科门类。每个模型完成1,000道随机抽样题目。绝对分数（0-100）代表原始表现，相对分数衡量与SOTA模型的差距。学科分数10分制。GPT-4 Turbo评判，每题0-3分。",
    "lb.about.med": "LLMEval-Med（EMNLP 2025）：2,996道来自真实电子病历和临床场景的题目，覆盖5个维度（MK、MLU、MR、MSE、MTG）。可用率(%) = 自动评测4分以上(0-5量表)或人工评测5分以上(0-7量表，MTG)的比例。人机一致率92.36%。",
    "lb.about.eval1": "LLMEval-1（AAAI 2024）：17大类、453题，五维评测（正确性、流畅性、信息量、逻辑性、无害性，0-3分）。2,186名公众标注者贡献243,337条标注，另提供对比评分（0-1）。",
    "lb.about.eval2": "LLMEval-2（AAAI 2024）：12个学科、480题，客观题（最高5分）+主观题（最高14分），总分归一化到0-100。",
    "lb.submit": "想提交模型进行评测？请联系我们：",
    "lb.or": "",
    "lb.search": "搜索模型...",
    "lb.allTypes": "全部类型",

    "blog.title": "博客",
    "blog.desc": "LLMEval 团队的最新动态与公告。",
    "blog.empty": "暂无博文，敬请期待！",
    "blog.readMore": "阅读全文",
    "blog.back": "返回博客",

    "footer.desc": "复旦大学NLP实验室·大语言模型综合评测框架。",
    "footer.research": "研究",
    "footer.links": "链接",
    "footer.contact": "联系我们",
    "footer.github": "GitHub 组织",
    "footer.platform": "LLMEval 评测平台",
    "footer.copyright": "LLMEval 项目 · 复旦大学NLP实验室 版权所有",

    "common.all": "全部",
  },
} as const;

export type Locale = "en" | "zh";
export type DictKey = keyof (typeof dict)["en"];
export default dict;
